posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns= [
    path('', views.posts_list, name="list"),
    path('create/', views.posts_create, name='create'),
    path('drafts/', views.posts_drafts, name='posts_drafts'),
    path('<int:id>/', views.posts_detail, name="posts_detail"),
    path('<int:id>/update/', views.posts_update, name="update"),
    path('<int:id>/delete/', views.posts_delete, name='delete'),

]

trydjango19/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save 
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.


class PostManager(models.Manager):
    def draft(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=True).filter(publish__gte=timezone.now())

    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

class Post(models.Model):
    user         = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title        = models.CharField(max_length=120)
    image        = models.ImageField(upload_to="images/", null=True, blank=True, height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field  = models.IntegerField(default=0)
    content      = models.TextField()
    draft        = models.BooleanField(default=False)
    publish      = models.DateField(auto_now=False, auto_now_add=False)
    updated      = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp    = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:posts_detail', kwargs={'id':self.id})


    class Meta:
        ordering = ['-timestamp', '-updated']

posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'draft', 'publish']

posts/views.py
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Post
from .forms import PostForm
# Create your views here.

@login_required
def posts_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "New post was successfully created")
        return redirect(instance.get_absolute_url())
    context = {'form': form}
    return render(request, 'post_create.html', context)

def posts_detail(request, id=None):
    today = timezone.now().date()
    obj = get_object_or_404(Post, id=id)
    if obj.publish > today or obj.draft:
        raise Http404
    context = {
        'obj': obj,
    }
    return render(request, 'post_detail.html', context)

def posts_list(request):
    today = timezone.now().date()
    queryset = Post.objects.active()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)

        ).distinct()
    paginator = Paginator(queryset, 10)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    queryset = paginator.get_page(page)

    context = {'queryset':queryset, "page_request_var":page_request_var, 'today':today}
    return render(request, 'post_list.html', context)

@login_required
def posts_update(request, id=None):
    obj = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully updated")
        return redirect(obj.get_absolute_url())
    context = {
        'obj': obj,
        'form':form
    }
    return render(request, 'post_form.html', context)
@login_required
def posts_delete(request, id=None):
    obj = get_object_or_404(Post, id=id)
    obj.delete()
    messages.success(request, "Post was successfully deleted")
    return redirect('posts:list')

@login_required
def posts_drafts(request):
    today = timezone.now().date()
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)

        ).distinct()
    paginator = Paginator(queryset, 10)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    queryset = paginator.get_page(page)

    context = {'queryset':queryset, "page_request_var":page_request_var, 'today': today}
    return render(request, 'post_drafts.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block head %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v3.1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class='page-header'>
      <a href="/" class="home"> Blog </a>
      {% if user.is_authenticated %}
        <a href="{% url 'posts:posts_drafts' %}" class="btn btn-default" id="drafts">Drafts</a>
        <a href="{% url 'posts:create' %}" class="btn btn-success" id="create" style="margin-right:5px;">Create new post</a>
      {% endif %}
    </div>

    {% include "messages_display.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

templates/messages_display.html
    <div class="messages">
      {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
      {% endif %}
    </div>

templates/post_create.html
{% extends "base.html" %}

{% block head %}Create Post{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offest-3">
  <h2>Form</h2>
    <form method="post" enctype="multipart/form-data" autocomplete="off"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Create post">
    </form>
</div>
{% endblock %}

templates/post_detail.html
{% extends "base.html" %}

{% block head %}Detail{% endblock %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
      {% if obj.image %}
          {% if obj.user.get_full_name %}
            <p>{% if user.is_authenticated %}<a href="{% url 'posts:update' id=obj.id %}" class="btn btn-primary btn-xs">Обновить пост</a>{%endif%}Author: {{ obj.user.get_full_name }} {% if user.is_authenticated %}<a href="{% url 'posts:delete' id=obj.id %}" class="btn btn-danger btn-xs">Удалить пост</a>{%endif%} </p>
            <img src="{{ obj.image.url }}" alt="" class="img-resp">
          {% else %}
            <p>{% if user.is_authenticated %} <a href="{% url 'posts:update' id=obj.id %}" class="btn btn-primary btn-xs">Обновить пост</a>{%endif%} Author: {{ obj.user }} {% if user.is_authenticated %}<a href="{% url 'posts:delete' id=obj.id %}" class="btn btn-danger btn-xs">Удалить пост</a>{%endif%} </p>
            <img src="{{ obj.image.url }}" alt="" class="img-resp">
          {% endif %}
          <h2>{{ obj.title }} <small>{{ obj.publish }}</small> </h2>
          {{ obj.content|linebreaks }}<br>
      {% else %}
          {% if obj.user.get_full_name %}
            <p>{% if user.is_authenticated %}<a href="{% url 'posts:update' id=obj.id %}" class="btn btn-primary btn-xs">Обновить пост</a>{%endif%}Author: {{ obj.user.get_full_name }} {% if user.is_authenticated %}<a href="{% url 'posts:delete' id=obj.id %}" class="btn btn-danger btn-xs">Удалить пост</a>{%endif%} </p>
          {% else %}
            <p>{% if user.is_authenticated %}<a href="{% url 'posts:update' id=obj.id %}" class="btn btn-primary btn-xs">Обновить пост</a>{%endif%}Author: {{ obj.user }} {% if user.is_authenticated %}<a href="{% url 'posts:delete' id=obj.id %}" class="btn btn-danger btn-xs">Удалить пост</a>{%endif%} </p>
          {% endif %}
          <h2>{{ obj.title }} <small>{{ obj.publish }}</small> </h2>
          {{ obj.content|linebreaks }}<br>
      {% endif %}

      <p><div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div></p>

      <div class="row">
        <p><div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div></p>
      </div>

    </div>

{% endblock %}

templates/post_drafts.html
{% extends "base.html" %}

{% block head %}Drafts{% endblock %}

{% block content %}

<div class="col-sm-6 col-sm-offset-4">
  <form method="GET">
    <input type="text" name='q' placeholder='Search posts' value='{{request.GET.q}}' autocomplete="off">
    <input type="submit" value="Search">
  </form>
  <br>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <div class="row">
  <h2>Posts</h2>

  {% for obj in queryset %}
      {% if obj.draft or obj.publish > today %}
        <div class="thumbnail">
          {% if obj.draft %} <h3 style="color:red;">Draft</h3> {% endif %} {% if obj.publish > today %} <h3 style="color:red;">Future post</h3>{% endif %}
          {% if obj.image %}
              <img src="{{ obj.image.url }}" alt="" class="img-resp">
          {% endif %}
          <div class="caption">
            <h3><a href="{{obj.get_absolute_url}}">{{ obj.title }}</a> <small>{{ obj.publish }}</small> </h3>
            {% if obj.user.get_full_name %}
              <p>Author: {{ obj.user.get_full_name }}</p>
            {% else %}
              <p>Author: {{ obj.user }}</p>
            {% endif %}
            <p>{{ obj.content|linebreaks|truncatechars:60}}</p>
            <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
          </div>
        </div>
      {% endif %}
  {% endfor %}
  <div class="pagination">
      <span class="step-links">
          {% if queryset.has_previous %}
              <a href="?{{page_request_var}}={{ queryset.previous_page_number }}&q={{request.GET.q}}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}
          </span>

          {% if queryset.has_next %}
              <a href="?{{page_request_var}}={{ queryset.next_page_number }}&q={{request.GET.q}}">next</a>
          {% endif %}
      </span>
  </div>

  </div>
</div>
{% endblock %}

templates/post_form.html
{% extends "base.html" %}

{% block head %}Update Post{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" autocomplete="off"> {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" name="" value="Update post">
    </form>

{% endblock %}

templates/post_list.html
{% extends "base.html" %}

{% block head %}Posts{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-4">
  <form method="GET">
    <input type="text" name='q' placeholder='Search posts' value='{{request.GET.q}}' autocomplete="off">
    <input type="submit" value="Search">
  </form>
  <br>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <div class="row">
  <h2>Posts</h2>

  {% for obj in queryset %}
      <div class="thumbnail">
        {% if obj.draft %} <h3 style="color:red;">Draft{% if obj.publish > today %}, future post{% endif %}</h3> {% endif %}

        {% if obj.image %}
            <img src="{{ obj.image.url }}" alt="" class="img-resp">
        {% endif %}
        <div class="caption">
          <h3><a href="{{obj.get_absolute_url}}">{{ obj.title }}</a> <small>{{ obj.publish }}</small> </h3>
          {% if obj.user.get_full_name %}
            <p>Author: {{ obj.user.get_full_name }}</p>
          {% else %}
            <p>Author: {{ obj.user }}</p>
          {% endif %}
          <p>{{ obj.content|linebreaks|truncatechars:60}}</p>
          <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
        </div>
      </div>
  {% endfor %}

      <div class="pagination">
          <span class="step-links">
              {% if queryset.has_previous %}
                  <a href="?{{page_request_var}}={{ queryset.previous_page_number }}&q={{request.GET.q}}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}
              </span>

              {% if queryset.has_next %}
                  <a href="?{{page_request_var}}={{ queryset.next_page_number }}&q={{request.GET.q}}">next</a>
              {% endif %}
          </span>
      </div>
    </div>
</div>


{% endblock %}